#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='[\u@\h \W]\$ '

# Dotdrop Git Integration

export DOTREPO="~/Dokumenty/dotfiles"

alias dotdrop="$DOTREPO/dotdrop.sh"
alias dotgit="git -C $DOTREPO"
alias dotsync="dotgit pull && dotgit add -A && dotgit commit && dotgit push; dotdrop install"

export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock

# Install zoxide
eval "$(zoxide init bash)"