import = ['~/.config/alacritty/themes/catppuccin-mocha.toml']
shell = "nu"

[env]
TERM = "xterm-256color"

[window]
# None, Full
decorations = "none"
dynamic_padding = true
padding.x = 15
padding.y = 15

[font]
# fc-list: family style | grep "Cozette"
size = 8

[font.normal]
# family = "JetBrains Mono"
# family = "Scientifica"
family = "Cozette"
# family = "Tamzen"
style = "Regular"

[font.bold]
style = "Medium"

[cursor]
style.blinking = "On"
