[tools]
bun = "latest"
deno = "latest"
java = "latest"
python = "3.11"
terraform = "latest"
opentofu = "latest"
rye = "latest"
uv = "latest"
pnpm = "latest"
yarn = "latest"
dprint = "latest"
ripgrep = "latest"
dust = "latest"
bat = "latest"
swift = "latest"
